<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 /home/lukas/webstorm-projects/voyager/models/marco-polo-bust.glb --transform --types --suspense
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useGltf, useSuspense } from '@threlte/extras';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	const suspend = useSuspense();

	type GLTFResult = {
		nodes: {
			model_0: THREE.Mesh;
			model_1: THREE.Mesh;
			model_2: THREE.Mesh;
			model_3: THREE.Mesh;
		};
		materials: {
			['Marco Polo']: THREE.MeshStandardMaterial;
		};
	};

	const gltf = suspend(useGltf<GLTFResult>('/marco-polo-bust-transformed.glb'));
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.model_0.geometry}
			material={gltf.materials['Marco Polo']}
			position={[0, 10.7, 0]}
			rotation={[-Math.PI, 0, 0]}
		/>
		<T.Mesh
			geometry={gltf.nodes.model_1.geometry}
			material={gltf.materials['Marco Polo']}
			position={[0, 10.7, 0]}
			rotation={[-Math.PI, 0, 0]}
		/>
		<T.Mesh
			geometry={gltf.nodes.model_2.geometry}
			material={gltf.materials['Marco Polo']}
			position={[0, 10.7, 0]}
			rotation={[-Math.PI, 0, 0]}
		/>
		<T.Mesh
			geometry={gltf.nodes.model_3.geometry}
			material={gltf.materials['Marco Polo']}
			position={[0, 10.7, 0]}
			rotation={[-Math.PI, 0, 0]}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
