<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0 /home/lukas/webstorm-projects/voyager/models/haenke.glb --transform --resolution 4096 --types --suspense
-->

<script lang="ts">
	import type * as THREE from 'three';

	import type { Snippet } from 'svelte';
	import { T, type Props } from '@threlte/core';
	import { useSuspense } from '@threlte/extras';
	import { useGltf } from '$lib/utils';
	import { ModelDialog } from '$lib/components/models/index';
	import text from '$lib/texts/tadeas-haenke.html?raw';

	let {
		fallback,
		error,
		children,
		ref = $bindable(),
		...props
	}: Props<THREE.Group> & {
		ref?: THREE.Group;
		children?: Snippet<[{ ref: THREE.Group }]>;
		fallback?: Snippet;
		error?: Snippet<[{ error: Error }]>;
	} = $props();

	const suspend = useSuspense();

	type GLTFResult = {
		nodes: {
			mona_lisa002: THREE.Mesh;
			mona_lisa000: THREE.Mesh;
			mona_lisa001: THREE.Mesh;
			mona_lisa026: THREE.Mesh;
			Plane: THREE.Mesh;
		};
		materials: {
			Frame: THREE.MeshStandardMaterial;
			Image: THREE.MeshStandardMaterial;
		};
	};

	const gltf = suspend(useGltf<GLTFResult>('/haenke-transformed.glb'));
</script>

<ModelDialog model={ref} {text} />

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.mona_lisa002.geometry}
			material={gltf.materials.Frame}
			position={[-0.53, -0.59, -0.05]}
			rotation={[-1.56, 0, -3.14]}
			scale={[1.21, 1.9, 1.39]}
		/>
		<T.Mesh
			geometry={gltf.nodes.mona_lisa000.geometry}
			material={gltf.materials.Frame}
			position={[-0.53, 0.7, -0.04]}
			rotation={[1.58, 0, 0]}
			scale={[1.21, 1.9, 1.39]}
		/>
		<T.Mesh
			geometry={gltf.nodes.mona_lisa001.geometry}
			material={gltf.materials.Frame}
			position={[-1.14, 0.05, -0.05]}
			rotation={[-2.83, 1.57, -1.88]}
			scale={[1.39, 1.9, 1.9]}
		/>
		<T.Mesh
			geometry={gltf.nodes.mona_lisa026.geometry}
			material={gltf.materials.Frame}
			position={[0.01, 0.41, -0.02]}
			rotation={[0.32, -1.57, -1.26]}
			scale={[1.39, 1.9, 1.9]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Plane.geometry}
			material={gltf.materials.Image}
			position={[-0.53, 0.05, -0.11]}
			rotation={[Math.PI / 2, 0, 0]}
			scale={[0.46, 0.46, 0.53]}
		/>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
